#!/bin/bash

# Project File Structure Summary
# Google Dorking Security Tool

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         Google Dorking Tool - Project Files Summary            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📁 Project Root: /home/prem/google-dorking/"
echo ""

echo "📄 Core Application Files:"
echo "  ├── run.py                    - Flask development server entry point"
echo "  ├── worker.py                 - Celery worker entry point"
echo "  ├── config.py                 - Configuration management"
echo "  └── tests.py                  - Unit tests"
echo ""

echo "📚 Documentation Files:"
echo "  ├── README.md                 - Complete documentation (400+ lines)"
echo "  ├── QUICKSTART.md             - 5-minute setup guide"
echo "  ├── API.md                    - API reference & examples"
echo "  ├── DOCKER.md                 - Docker deployment guide"
echo "  ├── .env.example              - Example environment variables"
echo "  ├── .env                      - Ready-to-use environment config"
echo "  └── Makefile                  - 15+ convenient commands"
echo ""

echo "🐍 Application Package (app/):"
echo "  ├── __init__.py               - Flask app factory & CORS setup"
echo "  ├── routes.py                 - 13 API endpoints + web routes"
echo "  ├── dorking_queries.py        - 256+ queries in 23 categories"
echo "  ├── search_engine.py          - Google search implementation"
echo "  ├── tasks.py                  - Celery background tasks"
echo "  │"
echo "  ├── templates/                - HTML templates"
echo "  │   ├── index.html            - Main page"
echo "  │   ├── results.html          - Results display & export"
echo "  │   └── help.html             - Help & documentation page"
echo "  │"
echo "  └── static/                   - Static assets"
echo "      ├── css/style.css         - Bootstrap 5 + custom styles"
echo "      └── js/main.js            - JavaScript utilities"
echo ""

echo "🐳 Docker Files:"
echo "  ├── Dockerfile               - Flask app containerization"
echo "  └── docker-compose.yml       - Multi-service orchestration"
echo ""

echo "📦 Dependency Files:"
echo "  ├── requirements.txt          - Python dependencies (10 packages)"
echo "  └── setup.sh                  - Automated setup script"
echo ""

echo "🔑 Git Files:"
echo "  └── .gitignore               - Git ignore patterns"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📊 Project Statistics:"
echo "  ├── Python files: 9"
echo "  ├── HTML templates: 3"
echo "  ├── Dorking queries: 256+"
echo "  ├── Query categories: 23"
echo "  ├── API endpoints: 13"
echo "  ├── Documentation files: 5"
echo "  ├── Total lines of code: 3000+"
echo "  └── Total files: 24"
echo ""

echo "🎯 Key Features:"
echo "  ✓ Web-based user interface"
echo "  ✓ 256+ pre-built dorking queries"
echo "  ✓ Background task execution (Celery + Redis)"
echo "  ✓ Real-time progress tracking"
echo "  ✓ Results export (JSON/CSV)"
echo "  ✓ Comprehensive REST API"
echo "  ✓ Docker deployment support"
echo "  ✓ Mobile-responsive design"
echo "  ✓ Complete documentation"
echo "  ✓ Automated setup scripts"
echo ""

echo "🚀 Quick Start:"
echo "  1. bash setup.sh"
echo "  2. source venv/bin/activate"
echo "  3. python run.py (Terminal 1)"
echo "  4. python worker.py (Terminal 2)"
echo "  5. Open http://localhost:5000"
echo ""

echo "🐳 Docker Quick Start:"
echo "  docker-compose up -d"
echo "  Open http://localhost:5000"
echo ""

echo "════════════════════════════════════════════════════════════════"
